from tkinter import *
root=Tk()
w,k=root.winfo_screenwidth(),root.winfo_screenheight()
root.geometry('%dx%d+0+0'%(w,k))
root.title("Bus Ticketing System")
img=PhotoImage(file='.\\Bus_for_project.png')
Label(root,image=img).grid(row=0,column=0,columnspan=5,padx=w//3)
Button(root,text="Online Bus Ticketing System",font='Arial 14 bold',fg='red',bg='LightSkyBlue1').grid(row=1,column=0,columnspan=5,padx=w//3)
Label(root,text='Add Bus Operator Detail',font='Arial 20 bold',fg='green').grid(row=3,column=0,columnspan=5,padx=w//3,pady=50)
Label(root,text='Operator Id',font='Arial 12 bold').grid(row=7,column=0,pady=50)
Label(root,text='Name',font='Arial 12 bold').grid(row=7,column=1,pady=50)
Label(root,text='Address',font='Arial 12 bold').grid(row=7,column=2,pady=50)
Label(root,text='Phone No.',font='Arial 12 bold').grid(row=7,column=3,pady=50)
Label(root,text='Email',font='Arial 12 bold').grid(row=7,column=4,pady=50)
Button(root,text="ADD",font='Arial 14 bold',fg='black',bg='Green2').grid(row=7,column=6)
Button(root,text="EDIT",font='Arial 14 bold',fg='black',bg='Orange').grid(row=7,column=7)
img1=PhotoImage(file='.\\home.png')
Button(root,image=img1).grid(row=8,column=8)
root.mainloop()
