from tkinter import *
root=Tk()
w,k=root.winfo_screenwidth(),root.winfo_screenheight()
root.geometry('%dx%d+0+0'%(w,k))
root.title("Bus Ticketing System")
img=PhotoImage(file='.\\Bus_for_project.png')
Label(root,image=img).grid(row=0,column=1,columnspan=8,padx=w//2.5)
Button(root,text="Online Bus Ticketing System",font='Arial 14 bold',fg='red',bg='LightSkyBlue1').grid(row=1,column=1,columnspan=10)
Button(root,text="Enter Journey Details",font='Arial 14 bold',fg='red',bg='lightgreen').grid(row=2,column=1,columnspan=10)
Label(root,text="To",font='Arial 14 bold',fg="black").grid(row=3,column=1,sticky=E)
Entry(root).grid(row=3,column=2,sticky=W)
Label(root,text="From",font='Arial 14 bold').grid(row=3,column=3,sticky=E)
Entry(root).grid(row=3,column=4,sticky=W)
Label(root,text="Journey",font='Arial 14 bold').grid(row=3,column=5,sticky=E)
Entry(root).grid(row=3,column=6,sticky=W)
Button(root,text='SHOW BUSES',fg='Black',bg='Green').grid(row=3,column=7)
img1=PhotoImage(file='.\\home.png')
Button(root,image=img1).grid(row=3,column=8)
root.mainloop()
